config/routes.rb
Rails.application.routes.draw do
  resources :videos

  root 'videos#index'
  resources :videos

end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new

    @video.ct_id = params[:myCamera][:video_uuid]
    @video.thumbnail_url = params[:myCamera][:qvga][:small_thumb]
    @video.mp4_url = params[:myCamera][:qvga][:mp4]

    respond_to do |format|
      if @video.save
        format.html { redirect_to videos_url, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CtHerokuTest</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src='//cameratag.com/api/v5/js/cameratag.js' type='text/javascript'></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ct_id %><br>
    <%= f.text_field :ct_id %>
  </div>
  <div class="field">
    <%= f.label :thumbnail_url %><br>
    <%= f.text_field :thumbnail_url %>
  </div>
  <div class="field">
    <%= f.label :mp4_url %><br>
    <%= f.text_field :mp4_url %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videos</h1>

<hr>
<%= link_to 'New Video', new_video_path %>
<hr>

<% @videos.each do |video| %>
  <a href="<%= video_url(video) %>">
    <img src="<%= video.thumbnail_url %>"></img>
  </a>
<% end %>

<script>
$("img")
  .on('error', function() { console.log( $(this).attr("src", "<%= asset_url('processing.jpg') %>") ) });
</script>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <camera id="myCamera" data-app-id="<%= CAMERATAG_APPLICATION_UUID %>"></camera>
  
  <script>
    $(function(){
      CameraTag.observe("myCamera", "published", function(){
        $("#new_video").submit();
      })
    })
  </script>
<% end %>


<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', videos_path %>

<video id="myVideo" data-uuid="<%= @video.ct_id %>"></video>


<p>
  <strong>Ct:</strong>
  <%= @video.ct_id %>
</p>

<p>
  <strong>Thumbnail url:</strong>
  <%= @video.thumbnail_url %>
</p>

<p>
  <strong>Mp4 url:</strong>
  <%= @video.mp4_url %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Destroy', @video, method: :delete, data: { confirm: 'Are you sure?' } %>